import { readdirSync, readFileSync, writeFileSync, existsSync, unlinkSync } from 'fs';
import { basename, join } from 'path';
import { camelCaseFilename } from '../src/util.js';

const DYNAMIC_TYPES_FILE = 'src/data.GENERATED.ts';
const DATA_DIRECTORY = 'data';

// Stale compiled siblings of the generated file shadow the .ts at module-load
// time under the ts-node ESM loader (see the modeling stress-test notes). Wipe
// them on every regenerate so any iteration on the union types is consistent.
const STALE_SIBLINGS = ['.js', '.js.map', '.d.ts', '.d.ts.map'];
const stripStaleGenerated = () => {
	const base = DYNAMIC_TYPES_FILE.replace(/\.ts$/, '');
	for (const ext of STALE_SIBLINGS) {
		const p = base + ext;
		if (existsSync(p)) {
			try { unlinkSync(p); } catch { /* best-effort cleanup */ }
		}
	}
};

// Maps the public DataFilename key to its on-disk path relative to data/ and
// the basename used for module variable + sidecar matching.
type Datafile = { key : string, relPath : string, baseName : string };

const generateConfig = () => {
	const datafiles : Datafile[] = [];
	const sidecars : Datafile[] = [];

	// Scan a directory for .ts and .edits.json files. `keyPrefix` is the
	// namespace prefix in DataFilename keys (empty for top-level, 'private__'
	// for the gitignored private maps directory). `pathPrefix` is the on-disk
	// path prefix relative to data/.
	const scan = (subdir : string, keyPrefix : string, pathPrefix : string) => {
		for (const file of readdirSync(join(DATA_DIRECTORY, subdir))) {
			if (file.endsWith('.edits.json')) {
				const baseName = basename(file, '.edits.json');
				sidecars.push({ key: keyPrefix + baseName, relPath: pathPrefix + file, baseName });
				continue;
			}
			if (!file.endsWith('.ts')) continue;
			if (file.endsWith('.d.ts')) continue;
			const baseName = basename(file, '.ts');
			if (baseName.includes('SAMPLE')) continue;
			datafiles.push({ key: keyPrefix + baseName, relPath: pathPrefix + file, baseName });
		}
	};

	scan('', '', '');
	// Private maps live in a separate, gitignored git repo cloned into
	// data/private/. See docs/superpowers/notes/2026-05-12-private-maps-workflow.md.
	// Keys are namespaced as 'private__<name>' to avoid collisions and URL
	// path-segment issues.
	if (existsSync(join(DATA_DIRECTORY, 'private'))) {
		scan('private', 'private__', 'private/');
	}

	// Inline sidecar JSON content rather than importing it: web-dev-server serves
	// .json files with MIME application/json, which the browser rejects for ES
	// module imports. Inlining sidesteps the loader entirely and keeps the
	// generated file self-contained.
	const dataKeys = new Set(datafiles.map(d => d.key));
	const matchedSidecars = sidecars.filter(s => dataKeys.has(s.key));
	const sidecarEntries = matchedSidecars.map(s => {
		const raw = readFileSync(join(DATA_DIRECTORY, s.relPath), 'utf8');
		// Validate it parses, then re-stringify with consistent indentation.
		const parsed = JSON.parse(raw);
		const pretty = JSON.stringify(parsed, null, '\t').replace(/\n/g, '\n\t');
		return `\t'${s.key}': ${pretty}`;
	}).join(',\n');

	const importVar = (d : Datafile) => camelCaseFilename(d.key) + 'Data';
	const importPath = (d : Datafile) => `../data/${d.relPath.replace(/\.ts$/, '.js')}`;

	const data = `//This file was generated by 'npm run generate:config'

//We import all data files directly into the build because they aren't that big
//and this way we can get direct typescript type checking at compile time.

import {
	RawMapDefinition,
	RawScenariosDefinition
} from './types.js';

${datafiles.map(d => `import ${importVar(d)} from '${importPath(d)}';`).join('\n')}

export type DataFilename = ${datafiles.map(d => `'${d.key}'`).join(' | ')};

export const DATA : {[filename in DataFilename]: RawMapDefinition} = {
${datafiles.map(d => `\t'${d.key}': ${importVar(d)}`).join(',\n')}
};

export const SIDECAR_EDITS : Partial<{[filename in DataFilename]: RawScenariosDefinition}> = {
${sidecarEntries}
};
`;

	stripStaleGenerated();
	writeFileSync(DYNAMIC_TYPES_FILE, data);
};

generateConfig();